### PR TITLE
add updated routes

### PR DESCRIPTION
**Pull request by JenMcD-star**

### CODE REVIEW

**Review by jamisonvalentine — CHANGES_REQUESTED** [review]
I got `MODULE_NOT_FOUND` errors and had to install `bcryptjs` and `jsonwebtoken` so those may need to be added to the `package.json`

Also, got this error:
```
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
```

...which I'm assuming is because the `process.env.MONGO_URI` is not set on my machine. It would be helpful to share those details with the team (probably via slack)

**Comment by JenMcD-star** [comment]
Yes, I can share that .env file in slack.

I'll add those to the package json. I might have it globally installed on
my local because it's all running okay for me.

**Comment by jamisonvalentine** [comment]
Thanks for adding those dependencies. Just waiting on the `.env` file before approving

**Review by jamisonvalentine — APPROVED** [review]
Great job

**Review by Count-MonteCristo — APPROVED** [review]

**Pull request merged**
